package com.healthapp.ehr.domain.enums;

/**
 * Types of vital signs.
 */
public enum VitalType {
    BLOOD_PRESSURE_SYSTOLIC,
    BLOOD_PRESSURE_DIASTOLIC,
    HEART_RATE,
    RESPIRATORY_RATE,
    TEMPERATURE,
    OXYGEN_SATURATION,
    WEIGHT,
    HEIGHT,
    BMI,
    BLOOD_GLUCOSE,
    BLOOD_GLUCOSE_FASTING,
    BLOOD_GLUCOSE_POSTPRANDIAL,
    CHOLESTEROL_TOTAL,
    CHOLESTEROL_HDL,
    CHOLESTEROL_LDL,
    TRIGLYCERIDES,
    HEMOGLOBIN,
    CREATININE,
    URIC_ACID,
    PEAK_FLOW,
    WAIST_CIRCUMFERENCE
}
