package com.healthapp.notification.domain;

public enum NotificationType {
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    APPOINTMENT_REMINDER,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_RESCHEDULED,
    PAYMENT_SUCCESS,
    PAYMENT_RECEIVED,
    PAYMENT_FAILED,
    REFUND_PROCESSED,
    DOCTOR_REGISTRATION,
    VERIFICATION_COMPLETE,
    PASSWORD_RESET,
    OTP,
    PROMOTIONAL
}
